package com.cnpc.pms.reportFiledown.entity;

import com.cnpc.pms.base.entity.DataEntity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

/**
 * Created by Administrator on 2018/10/19.
 */
@Entity
@Table(name = "t_report_filedown")
public class TReportFiledown extends DataEntity {


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_filedown.filename
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */
    @Column(name="filename",length= 200 )
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_filedown.username
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */
    @Column(name = "username", length = 200)
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_filedown.url
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */
    @Column(name = "url", length = 200)
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_filedown.down_time
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */
    @Column(name = "down_time")
    private Date downTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_filedown.down_times
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */
    @Column(name = "down_times")
    private Integer downTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_filedown.description
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */
    @Column(name = "description", length = 200)
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_filedown.mark_1
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */
    @Column(name = "mark_1", length = 200)
    private String mark1;//mark1:0未生成文件，

    @Column(name = "table_logic", length = 20)
    private String tableLogic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_filedown.id
     *
     * @return the value of t_report_filedown.id
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_filedown.id
     *
     * @param id the value for t_report_filedown.id
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_filedown.filename
     *
     * @return the value of t_report_filedown.filename
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_filedown.filename
     *
     * @param filename the value for t_report_filedown.filename
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_filedown.username
     *
     * @return the value of t_report_filedown.username
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_filedown.username
     *
     * @param username the value for t_report_filedown.username
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_filedown.url
     *
     * @return the value of t_report_filedown.url
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_filedown.url
     *
     * @param url the value for t_report_filedown.url
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_filedown.down_time
     *
     * @return the value of t_report_filedown.down_time
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */
    public Date getDownTime() {
        return downTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_filedown.down_time
     *
     * @param downTime the value for t_report_filedown.down_time
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */
    public void setDownTime(Date downTime) {
        this.downTime = downTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_filedown.down_times
     *
     * @return the value of t_report_filedown.down_times
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */
    public Integer getDownTimes() {
        return downTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_filedown.down_times
     *
     * @param downTimes the value for t_report_filedown.down_times
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */
    public void setDownTimes(Integer downTimes) {
        this.downTimes = downTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_filedown.description
     *
     * @return the value of t_report_filedown.description
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_filedown.description
     *
     * @param description the value for t_report_filedown.description
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_filedown.mark_1
     *
     * @return the value of t_report_filedown.mark_1
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */
    public String getMark1() {
        return mark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_filedown.mark_1
     *
     * @param mark1 the value for t_report_filedown.mark_1
     *
     * @mbggenerated Tue Jan 30 18:43:26 CST 2018
     */
    public void setMark1(String mark1) {
        this.mark1 = mark1;
    }

    public String getTableLogic() {
        return tableLogic;
    }

    public void setTableLogic(String tableLogic) {
        this.tableLogic = tableLogic;
    }

}
